source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.4'

group :development, :test do
	# Use sqlite3 as the database for Active Record
	gem 'sqlite3'
	#用另一个测试框架RSpec来写整个测试用例
	gem 'rspec-rails'
end

#Gems used only for assets and not required in production environment by default.
group :assets do
	# Use SCSS for stylesheets
	gem 'sass-rails', '~> 4.0.2'

	# Use Uglifier as compressor for JavaScript assets
	gem 'uglifier', '>= 1.3.0'

	# Use CoffeeScript for .js.coffee assets and views
	gem 'coffee-rails', '~> 4.0.0'
end

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Capybara，这个 gem允许我们使用类似英语中的句法编写模拟与应用程序交互的代码。
group :test do
	gem 'capybara'
end

#我们还要把 PostgreSQL 所需的 gem 加入生产组，这样才能部署到 Heroku：
#Heroku 建议在开发环境和生产环境使用不同的数据库，不过对我们的示例程序而言没什么影响
#Heroku这是一个老牌的免费云空间了，无限流量和无限容量，但是它的受欢迎程度远不如OpenShift空间。部落直到今天才介绍Heroku免费空间也是有原因的，就是Heroku不支持PHP，数据库只有大小5MB。
#目前Heroku空间只支持Ruby, Node.js, Clojure, Java, Python, and Scala，创建项目和管理项目都需要安装Heroku Toolbelt工具，操作的难度都比较高，英文网站界面
#group :production do
	#gem 'pg'
#end

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
